### ISSUE TITLE
UI Re-Design/Finish

### ISSUE THREAD

**Issue by broc923** [broc923/capstone#5]
While I (Broc) was working on teh code, I had to move around a lot of the UI to actually get some things I needed (such as the picture box) on there. Make the UI pretty again, do the about page(our names and whatever else), and leave the login page alone unless you do a base UI.

**Comment by gsleezi** [comment]
About page contains developer names, picturebox for a logo when we decide on one.

**Comment by broc923** [comment]
Being reworked externally.
